### ISSUE TITLE
Remote Screenly

### ISSUE THREAD

**Issue by HunterZeroSix** [didiatworkz/screenly-ose-monitor#10]
Hi
is it possible to add a screen via a SSH Tunnel or VPN 

What do you think about it?
I found this manual https://www.rustimation.eu/index.php/reverse-ssh-tunnel-schritt-fur-schritt/

Best regards
HunterZeroSix

**Comment by didiatworkz** [comment]
Hello @HunterZeroSix 
this feature is planned in version 3 via php-ssh2
https://github.com/didiatworkz/screenly-ose-monitor/projects/2#card-27695466
