### ISSUE TITLE
ERROR! couldn't resolve module/action 'mount'. 

### ISSUE THREAD

**Issue by ismailakincom** [didiatworkz/screenly-ose-monitor#102]
<img width="941" alt="Screenshot at Nov 24 15-25-01" src="https://user-images.githubusercontent.com/6472427/203784210-eedcc071-b5da-4bfd-8f34-c662c6954864.png">

How can we solve this error?

**Comment by didiatworkz** [comment]
Hello @ismailakincom 
can you tell me which Ansible version do you use on the target system?
`ansible --version`

Best
