### ISSUE TITLE
Server IP Change After Installation

### ISSUE THREAD

**Issue by cerform** [didiatworkz/screenly-ose-monitor#104]
Hi , i have installed SOMO when Raspberry was connected with LAN cable , but all the players that i would like to manage is under wireless network that closed to internet access, now in SOMO settings server IP is wrong , can i change the server IP manually?
Thanks for you're help!

**Comment by didiatworkz** [comment]
Hello @cerform 
the server IP is the device IP.
If something wrong with them, you need to edit the service file: `/etc/systemd/system/docker.somo.service`

Best
didiatworkz
