### ISSUE TITLE
video upload video limit

### ISSUE THREAD

**Issue by ismailakincom** [didiatworkz/screenly-ose-monitor#109]
What's your question?
When I upload a video via somo, I get stuck in the video limit. How can we increase the somo video upload video limit?

**Comment by didiatworkz** [comment]
Settings -> System Settings -> Maximum asset upload size (MB)

**Comment by ismailakincom** [comment]
I increased the limit and the video appears to be loading. However, no video is sent to the device. It does not appear on the screen.why could it be?

**Comment by ismailakincom** [comment]
thanks @didiatworkz
