### ISSUE TITLE
Only URL as new asset

### ISSUE THREAD

**Issue by nsuva** [didiatworkz/screenly-ose-monitor#14]
Adding new assets in monitor page only allow URL. 
Is it possible to upload a video or image ? Where should we look fo add it in the code?

Thanks

**Comment by didiatworkz** [comment]
Hi @nsuva,
that's right. At the moment only urls work. The other methods are planned for version 3.
https://github.com/didiatworkz/screenly-ose-monitor/projects/2#card-27709022
Stay tuned ;) 

Best, 
didiatworkz

**Comment by nsuva** [comment]
Great ! Can´t wait to test it

**Comment by nsuva** [comment]
👏👏👏  
Works just fine inside local network. Tested images and videos and worked perfectly.
However if connected thru reverse tunneling to the monitor upload doesn't work. Seems to call directly the screen IP adress

**Comment by nsuva** [comment]
Hope this feedback help you :
When uploading a video, the duration of the asset is not written to the database.
This will not allow to change the status of the videos from active to inactive.
With images it works fine.

**Comment by didiatworkz** [comment]
Hi @nsuva,

Thanks for your Feedback, but the problem that you describe was another problem.
I fixed it in version 3.0 and close the ticket ;)
