### ISSUE TITLE
Edit Assets

### ISSUE THREAD

**Issue by nsuva** [didiatworkz/screenly-ose-monitor#15]
When editing some asset the duration neither the start/end date are saved.

**Comment by didiatworkz** [comment]
Hey @nsuva 
yes - I noticed this today, too..

Do you work in my company and was in the meeting today? :D
I will check this and fix this ;)

**Comment by didiatworkz** [comment]
Fixed https://github.com/didiatworkz/screenly-ose-monitor/releases/tag/v2.4

**Comment by didiatworkz** [comment]
Hey @nsuva 
I didn't see you comment...
For the next time open a new Issue, please.

You can rewrite the nginx config from screenly like this:
```
location /monitor {
	alias /var/www/html/monitor;
	try_files $uri $uri/ @monitor;

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_param SCRIPT_FILENAME $request_filename;
		fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
	}
}

location @monitor {
	rewrite /monitor/(.*)$ /monitor/index.php?/$1 last;
}

location ~ \.php$ {
	include snippets/fastcgi-php.conf;
	fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
}
```
add this code to /etc/nginx/sites-enabled/screenly.conf before the last bracket }
Now you need the address: http://localhost/monitor/index.php
It is a quick and dirty solution.. For more information you can search for: PHP Apps in a Subdirectory in Nginx

Best,
didiatworkz

**Comment by nsuva** [comment]
Thanks Mate !  
Meanwhile I thought in something similar and have been testing. Will adapt it with the code you provided. 
It seems to work and be able to use only one port for the reverse tunnel connection. 

Thanks
