### ISSUE TITLE
Screen image preview outside local network

### ISSUE THREAD

**Issue by nsuva** [didiatworkz/screenly-ose-monitor#24]
Tested all the functions from outside local network over ssh reverse tunnel to monitor:9000

Almost everything works fine, however image preview of the screens doesn't work. Do you know any way that I can change the image url so that not going directly to the ip adress of the screen?

I've read in some answer you gave to other post that you're implementing php-ssh2. Can this be a solutions for the issue ?

Thanks

**Comment by didiatworkz** [comment]
Hi @nsuva 
php2-ssh will only use for execute commands on the players.
The monitoring is currently only designed for use in a  intranet/private network.
Maybe in the future it will be possible to use it in another scenarios.
Sry...

Best
didiatworkz

**Comment by nsuva** [comment]
I've made some changes to your code and I was made it able to show the screenshots from reverse tunnel outside local network.
The refresh function capture all screen images to a folder and refreshes the page with this images. 
Of course it is not for a real time screen preview usage, but with 5-10 seconds refresh time it works fine.  
Just let me know if you want me to commit my code.

**Comment by didiatworkz** [comment]
Hey @nsuva 
i have integrated a new system in version 3.0 how the players are checked. See if it is a solution for you. But remember that version 3.0 is still in beta stage!
