### ISSUE TITLE
Upload Asset to multiple devices

### ISSUE THREAD

**Issue by stephenmcc91** [didiatworkz/screenly-ose-monitor#26]
Would it be possible to add or edit assets to multiple devices at once? 

There's a UWP app available for OSE that supports this, but it's not great.

**Comment by didiatworkz** [comment]
Hi @stephenmcc91 
That sounds like an interesting idea.
I will consider whether and how I could integrate it.
But it will be after version 3.

Best
didiatworkz

**Comment by neilyboy** [comment]
Would be very interested in this myself! I love this project so far! Thank you for all of your work on this project didiatworkz!
Neil

**Comment by rolandjanssen** [comment]
Is it possible to use it with balenacloud? Any tips are welcome, thnx
