### ISSUE TITLE
Youtube assets do not work.

### ISSUE THREAD

**Issue by neilyboy** [didiatworkz/screenly-ose-monitor#27]
When I load a youtube video via screenly-ose-monitor it fails to pull the content like it does while adding youtube content via direct screenly-ose interface.
![image](https://user-images.githubusercontent.com/9546844/71528166-39576d80-28a4-11ea-9890-cb6985e4c4d3.png)

Thank you again for your time on this!
Neil

**Comment by neilyboy** [comment]
btw. I have no idea what that video is lol (I just searched music video and used the first video that came up).

Neil

**Comment by didiatworkz** [comment]
Hi @neilyboy,
sorry for my late feedback.
I'm trying to reconstruct the error, but I can't.
Can you explain step by step how the error occurs?

Best,
Philipp
