### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Schubi1** [didiatworkz/screenly-ose-monitor#28]
I'm not sure if my problem is caused by the  response time of a screen. All my screens are connected via LTE Modem in an VPN Network. The screens ar often shown as offline, or when i klick them the are shown to be offline -but the are not!
Is there a way to wait for example 1 second for response of a screen?

Thanke you in advance,
Schubi

**Comment by didiatworkz** [comment]
Hi @Schubi1 
which version do you use at the moment?

**Comment by Schubi1** [comment]
Thank you so much for your fast reply! Yes i am using 2.4. But i am not particularly good in programming. I will try to find where to change this setting in the installed Version.
Thank you for your great work!!!
Schubi.

**Comment by Schubi1** [comment]
It doesn't seem to solve my problem. Screens are shown as offline - but the are not. When pressing the refreshbutton in your webinterface the are somtimes shown as online. When clicking on a screen i get somtimes access to the assets - sometimes not. But always it is possible to refresh one or more times - then it works.
First ping to the screens is always very long:
`PING 10.8.0.3 (10.8.0.3) 56(84) bytes of data.
64 bytes from 10.8.0.3: icmp_seq=1 ttl=64 time=2189 ms
64 bytes from 10.8.0.3: icmp_seq=2 ttl=64 time=1171 ms
64 bytes from 10.8.0.3: icmp_seq=3 ttl=64 time=151 ms
`

**Comment by didiatworkz** [comment]
Hi @Schubi1,
you have a pretty high ping to the players :/ 
I have rewritten the whole system in version 3.0 to make it run better - currently I'm testing it with 18 players, which still causes problems. 
In the current case it looks like the tunnel will not be established until you connect to it. So I assume that it will be a tunnel problem.

Best,
Philipp

**Comment by Schubi1** [comment]
Hi @didiatworkz 
no problem, if you find a solution i am more happy - but now i am also happy - just need to press reloadbutton one or two times, then it shows the right status.
I will try to do a permanent ping to the server to reduce the ping time.
As you said this could help, because one of the players has an additional router that does permanent ping 8.8.8.8 - this screen is shown 99% online.
I will give you further feedback, thank you very much!

Best regards,

Schubi
