### ISSUE TITLE
can I use the monitoring without installing screenly to my server?

### ISSUE THREAD

**Issue by anakuron** [didiatworkz/screenly-ose-monitor#3]
So did I understand this correctly, if I want to install the monitoring to my server and connect the players to it, I have to also install Screenly to the server?

**Comment by didiatworkz** [comment]
Hi anakuron,

Screenly installs some packages that my installation needs.
If you want to run it as a stand-alone instance, you will need to install the following first:

```bash
sudo mkdir -p /etc/ansible
echo -e "[local]\nlocalhost ansible_connection=local" | sudo tee /etc/ansible/hosts > /dev/null

sudo apt-get purge -y python-setuptools python-pip python-pyasn1
sudo apt-get install -y python-dev git-core libffi-dev libssl-dev
curl -s https://bootstrap.pypa.io/get-pip.py | sudo python
sudo pip install ansible==2.8.2
```

I didn't test that. Actually, the monitor is intended to be installed on a Screenly Player.

Best,
didiatworkz

**Comment by anakuron** [comment]
Thanks, I'll see if I get it to work, anyway this answers to my question and it's clear that (at least for now) it's intended to run in a player.
