### ISSUE TITLE
Displaying monitoring site at port 80

### ISSUE THREAD

**Issue by readyrockc** [didiatworkz/screenly-ose-monitor#30]
Not a bug. I need help getting the monitoring site displayed at port 80. Port 80 now shows the nginx welcome screen because i have installed ose-monitoring as a stand alone version.

Just changing the /etc/nginx/sites-enabled/monitoring.conf from "listen 9000;" to "listen 80;"  doesn't do the trick, it seems?

It is installed on "Debian Buster with Raspberry Pi Desktop" x86 version...

Thanks a lot! And really nice work btw. :)

**Comment by didiatworkz** [comment]
Hi @readyrockc 
nice to hear that you use my project.
Replace the line with in monitoring.conf with: ```listen 80 default_server;```
Restart the nginx service: ```sudo systemctl restart nginx.service```
And that's it ;)
If that didn't work, check if there are other configuration files in the "/etc/nginx/site-enabled/" folder and move or delete them.

Best,
didiatworkz

**Comment by readyrockc** [comment]
That's it! Works perfectly :)

**Comment by didiatworkz** [comment]
Nice to hear ;)
