### ISSUE TITLE
Issue with Updating from Version 2.4 to newest

### ISSUE THREAD

**Issue by tomber1022** [didiatworkz/screenly-ose-monitor#35]
First off, I'm a big fan of the program you made, it has made managing my screenly pis so much easier.

I'm not sure if this should be filed under a bug report or not since It may not be the fault of the program itself but when I go to update my pi, I get this error:

TASK [monitoring : Install packages] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://packagecloud.io/wott/agent/raspbian stretch Release' does no longer have a Release file."}

I'm think either the link is dead or there's problem on my end connecting to the repository.

Please let me know what you think.

**Comment by tomber1022** [comment]
Just clarify, I meant update the version of the of the Monitor. After the message, it says it completes but it still on version 2.4 when I check in using --version

**Comment by didiatworkz** [comment]
Hello @tomber1022 ,

Glad to hear that my tools help some other people :)

In your case you had installed the wott-agent package on the PI.

The Ansible Playbook will install the new packages and run and apt update before.
This is what happens the error.

When you enter the command: ```sudo apt update``` they must be shown a similar error.

You must remove this repo from the apt source.list or update this software manually: https://wott.io/documentation/getting-started

After that you can run the update and the Playbook will be run perfect. 

Let me know if you need more help. 
Best 
didiatworkz

**Comment by tomber1022** [comment]
Thank you! I finally got it to install.  But now I'm having issues with uploading and adding assets. I'm going to make a separate issue to keep it separated from this post.
