### ISSUE TITLE
Problems with Adding and Uploading Assets

### ISSUE THREAD

**Issue by tomber1022** [didiatworkz/screenly-ose-monitor#36]
I am unable to upload or add assets via URL. Whenever I attempt to, it says that my login information is incorrect. 

![Error](https://user-images.githubusercontent.com/67019463/85305623-efc29680-b472-11ea-8ccf-57eed1c42226.PNG)

I have tried deleting and adding the pi again and changing the username and password  to see if it  I could get it to work but I haven't found a solution yet. The only way I'v gotten it to add the assets is by disabling the password authentication for one my screenly and it work perfectly; but I don't want have to disable it permanently.

I don't think I'm entering the password/username wrong since I am able to see the other assets and the plugin feed.

**Comment by manosh7226** [comment]
Same issue here.

**Comment by didiatworkz** [comment]
Hello @tomber1022 and @manosh7226,


do you use the Multiuploader or do add a single asset to your Player?
Happend that issue on both methods? 

The user and password is needed when the Screenly Player Authentication is activated. Then you must enter the player authentication and not the SSH authentication.

I will check this tomorrow!

Best
didiatworkz

**Comment by manosh7226** [comment]
Yes tried Multiloader and single asset.  Used the Screenly Player Authentication and entered the player authentication. I can see the player on the monitor. I can reboot it too.  When I try to add asset I get the error above.

**Comment by didiatworkz** [comment]
Good morning :D 
Unfortunately I can reproduce the problem :( 

I will check the code and release an update for that.

Best
didiatworkz

**Comment by tomber1022** [comment]
@didiatworkz , I finally got a chance to test the update this morning. I can now upload assets to the pis, but multiloader is still not functioning as it should. When selecting multiple pis, it will only upload to the first pi that is selected on the list of pis. I can upload individually just fine.

**Comment by didiatworkz** [comment]
Hey ho @tomber1022 ,

Hhmm.. Can you check if that problem happened when you upload a URL via Multiuploader?

**Comment by tomber1022** [comment]
Uploading by URL works just fine using Multiuploader.

**Comment by didiatworkz** [comment]
Hello @tomber1022 ,

I think I found the mistake.
I will test it tomorrow in my production environment and release it if everything works.

Sorry for the trouble.

Best,
didiatworkz

**Comment by didiatworkz** [comment]
Hi @tomber1022 ,

new version is released - please update and give me a feedback :) 
I can't find any issues at the moment any more

**Comment by tomber1022** [comment]
Just tested it and it seems like you fixed it. Thank you!
