### ISSUE TITLE
Ability to Disable the Add-on

### ISSUE THREAD

**Issue by tomber1022** [didiatworkz/screenly-ose-monitor#40]
I like the add-on since it allows me to see  how my assets are displaying, but I was wondering if there was possible to disable or deactivate the add-on. It is really nice to have but, outside of when I initially add my assets, I would rather just have it say if the pi is active or not most of the time. 

I know that you can already control how often you receive a screenshot. I don't have much experience in programming for pis so I honestly do not how hard it would be to implement, but the way I'm imagining this would be an option in the setting or a button when you view the pi's assets that allows you to disable the add-on just for that select pi. 

I think you've done an amazing job and, like I said, I have no idea how hard it would be to do, so if you wanted to, you could honestly just complete disregard this and I honestly would not mind it one bit lol. I just thought that this could be neat addition if you were look for suggestions.

**Comment by didiatworkz** [comment]
Hello @tomber1022,

First of all, thanks for your feedback! This helps me a lot and I see that this project is also successfully used out there!

Back to your question:
There is no disabling of the add-on. Once installed, the add-on provides the image of the HDMI signal.
This means that the monitoring only looks at the available picture. If this is not the case, the "online" picture is displayed.

It would be technically no problem to implement this as an option, so you can deactivate it if necessary. But on the player itself the picture is always created as long as you don't uninstall the scripts.
Fun Fact: The picture is not stored on the micro SD card, but in RAM. This saves the card.

Why I did not install this is the following:
Screenly can sometimes hang up and the picture gets stuck or turns black when the service is not running anymore. The online check cannot detect this. The only way to see this is to see what is being output.

I will think about this idea in the next version when this help you ;)

Best,
didiatworkz

**Comment by didiatworkz** [comment]
Issue will be closed - Implemented in V4.0
