### ISSUE TITLE
Establish user and players relationship

### ISSUE THREAD

**Issue by jcsanchezrb** [didiatworkz/screenly-ose-monitor#41]
Would it be possible to make a specific user only view and manage a specific list of players? 

Only an admin user should be able to create, modify and delete this user -> players relationship.

**Comment by didiatworkz** [comment]
Hello @jcsanchezrb 

this is planned for Version 4 - A full right management for Admins ;)

**Comment by didiatworkz** [comment]
Issue will be closed - Implemented in V4.0
