### ISSUE TITLE
Add monitor name in the settings

### ISSUE THREAD

**Issue by jcsanchezrb** [didiatworkz/screenly-ose-monitor#42]
Would it be possible in the settings to add a monitor name, as Screenly OSE does, and then this name could be displayed later in the contents as Screenly OSE does?

**Comment by didiatworkz** [comment]
Hello @jcsanchezrb 
do you think that the name is read from the player and then displayed and set in the monitoring?
Or do you think that the name is set in the monitoring and then changes in the player?
In the second case, this is not possible because the Screenly OSE API does not support this function.

Best
didiatworkz

**Comment by jcsanchezrb** [comment]
Sorry, but I think I have not explained the enhancement correctly. 

I don't want change the player name of the one Screenly OSE (I know it isn't possible throughAPI), I want to add a new item in the setting to put a name to every Screenly OSE Monitoring, like you can do with an Screenly OSE player.

This way, if you have multiple Screenly OSE Monitoring, you can recognize each one.

**Comment by didiatworkz** [comment]
Hello @jcsanchezrb 
you didn't mean this: 
![name](https://user-images.githubusercontent.com/18490798/87301206-7406b780-c50f-11ea-9b0c-3a8987dd964b.gif)
right?

You mean that you can edit the name of the whole monitoring system - So you can manage multiple monitoring systems in one browser and you can find the right one in the tabs?

Sry, when I didn't understand your question :/ 

Best
didiatworkz

**Comment by jcsanchezrb** [comment]
Yes, I mean I can edit the name of the whole monitoring system, so I can manage multiple monitoring system......

**Comment by didiatworkz** [comment]
ok @jcsanchezrb  :D
I added this to the upcoming ideas

Best 
didiatworkz
