### ISSUE TITLE
Grey vertical lines with addon output

### ISSUE THREAD

**Issue by moridin1138** [didiatworkz/screenly-ose-monitor#43]
First off, thanks for the great addon to Screenly!  Your effort is much appreciated.  It works flawlessly with the exception of the video/HDMI addon.  Instead of showing the expected screen, it shows 2/3rds of the screen, but with an overlay of vertical grey lines.

I am running screenly on a Pi4 using screenly version 0.18.2.

![2020-07-18 14_35_04-Screenly OSE Monitoring and 3 more pages - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/25270032/87859633-95e3ae00-c904-11ea-95bd-d8bec5b906ba.png)
![2020-07-18 14_35_19-Screenly OSE Monitoring and 3 more pages - Profile 1 - Microsoft​ Edge](https://user-images.githubusercontent.com/25270032/87859634-9714db00-c904-11ea-8cfc-de294144bb4e.png)
![screenly_remote_hdmi](https://user-images.githubusercontent.com/25270032/87859713-38039600-c905-11ea-8b8c-c9e9421fa24d.png)

**Comment by didiatworkz** [comment]
Hello @moridin1138 

sorry for the late answer, but I'm on vacation :D
This is very interesting. I haven't been able to test the whole thing on a Raspberry Pi 4 yet because I don't have these devices in my test environment or productive system.

Which version of the Raspbian system are you using? -> 86bit / 64bit -- Buster?

If you reinstall the add-on, the error remains?

Best
didiatworkz

**Comment by moridin1138** [comment]
Hola didiatworkz,

We are using 32-bit Buster to get this going.  It was a bit of a hack because I got it working using a pre-Pi4 version of Screenly.  Will try a reinstall on a spare Pi and see if the issue persists.

Thanks,

-brian

**Comment by didiatworkz** [comment]
Hello @moridin1138 
now that I have bought a Raspberry Pi 4 and installed screenly (docker version).
Afterwards the ose-monitiring and the add-on. 
Everything worked without problems.

After no feedback and no problem I will close this issue.

Best didiatworkz
