### ISSUE TITLE
Bug with future dates in assets

### ISSUE THREAD

**Issue by jcsanchezrb** [didiatworkz/screenly-ose-monitor#44]
There is an error when Screenly OSE Monitoring gets an asset from a player, when reading and displaying some future dates.

[Screenly OSE Monitoring.docx](https://github.com/didiatworkz/screenly-ose-monitor/files/4980640/Screenly.OSE.Monitoring.docx)

**Comment by didiatworkz** [comment]
Hey @jcsanchezrb 
sorry for my late reply..
The problem occurs when the asset is set to "Forever".
Then the date is set to, for example, 9999-08-02. 
Currently, the system cannot handle this.
But I will take this into consider in the next version.

Can you confirm that?

Best
didiatworkz

**Comment by jcsanchezrb** [comment]
Yes, I confirm it
