### ISSUE TITLE
Multi Upload in Screen OSE not possible

### ISSUE THREAD

**Issue by kgansberger** [didiatworkz/screenly-ose-monitor#46]
its possible to select more than one image, but just uploading one image ...

**Comment by didiatworkz** [comment]
Hey :) 
sure - look at this gif...
![ezgif com-crop](https://user-images.githubusercontent.com/18490798/91062664-46904c00-e62d-11ea-9cd4-ee28b331122a.gif)


It 's also possible to drag 'n' drop the images into the upload zone.
Is this the answer of your question?

Best
didiatworkz

**Comment by didiatworkz** [comment]
Hello @kgansberger 
Are there any further questions or can we close the issue with this?

Best didiatworkz

**Comment by kgansberger** [comment]
hi didiatworkz,
sorry for missing answer.
I can upload multiple files as in your screenrec, but only one picture is in filelist after upload. only have one monitor. 
any idea?

**Comment by didiatworkz** [comment]
Hello @kgansberger 
I created a test setup and as you can see I tried to reproduce your problem.
Can you please check if you are using the latest version (v3.3) and if so, I would ask you to run the installation again.
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/18490798/92151709-e023de80-ee21-11ea-9455-64c6ccd37f9c.gif)

Best didiatworkz

**Comment by kgansberger** [comment]
v3.3, Updated second time, even now just one picture is in list ... 
![grafik](https://user-images.githubusercontent.com/1162770/92506749-33bd7000-f206-11ea-941b-3aa92d967b4e.png)

**Comment by didiatworkz** [comment]
Hello @kgansberger ,

can you create a video clip of the issue with an open DevTool -> Network (CTRL+SHIFT+J (https://www.freecodecamp.org/news/chrome-devtools-network-tab-tricks/))?
And can you tell me which browser do you use?

Best 
didiatworkz
