### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by jovalois** [didiatworkz/screenly-ose-monitor#49]
What's your question?

It does not show me the image of what the player is playing

**Comment by didiatworkz** [comment]
Hello @jovalois 
Do you installed the add-on on the target player?
```bash <(curl -sL https://git.io/Jf900)```

Best
didiatworkz

**Comment by jovalois** [comment]
If it was installed and it does not generate an error but it still seems that it is not installed, I am attaching an image
![Captura de pantalla de 2020-10-23 16-07-12](https://user-images.githubusercontent.com/73259245/97054720-ee9d9500-154a-11eb-96d5-541e378f1cf0.png)

**Comment by didiatworkz** [comment]
Hello @jovalois 

So let me get this straight...
You have also logged into player 192.168.1.82 via ssh and executed the command: ```bash <(curl -sL https://git.io/Jf900)```
If this is installed correctly, then a script must be here:
```/usr/bin/screenshot.sh```
a crontab can be found here: ```sudo crontab -e```
```sleep 20 && /usr/bin/screenshot.sh >> /var/log/screenshot.log 2>1```
and this command must also work: ```raspi2png --help```

If one of them doesn't fit, then you have to install the whole thing again and send me the complete output of the installation.

Best
didiatworkz

PS: 192.168.1.82:9020/screen/screenshot.png is the address to check, as soon as it is reachable, the image is retrieved

**Comment by didiatworkz** [comment]
No response from author - Issue will be closed
