### ISSUE TITLE
Install script on ubuntu 18.04

### ISSUE THREAD

**Issue by umityavz** [didiatworkz/screenly-ose-monitor#52]
When i try to install ın ubuntu 18:04 ihave this error message.  I wanna try to install standalone system.

TASK [monitoring : Create .monitor directory] ************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: failed to look up user pi", "owner": "root", "path": "/home/pi/.monitor", "size": 4096, "state": "directory", "uid": 0}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost : ok=1 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0

/dev/fd/63: line 79: /root/.monitor/latest_monitor: No such file or directory
Device "wlan0" does not exist.

Thanks

**Comment by didiatworkz** [comment]
Hello @umityavz 
I changed the working directory - You can run the installer again.
At the moment I create an Ubuntu VM to test this changes... 

Please hold the line 😄

**Comment by didiatworkz** [comment]
Ah ok.. I found some problems...

**Comment by umityavz** [comment]
Philipp you're very fast give to me answer, thanks man. I will try this one.

Thanks.

**Comment by didiatworkz** [comment]
I fixed the installation process now - You can install it :)
I will fix some other problem in V4.0
