### ISSUE TITLE
cloud server

### ISSUE THREAD

**Issue by c4rv88** [didiatworkz/screenly-ose-monitor#53]
Hi! first congratulations on the work, this is helping me a lot I wanted to know if you have any tips regarding my scenario.
I use a debian server in the cloud with the screenly monitor installed, the communication between the pi and the monitor is done through a vpn. The system can see the pi normally, even the addon works perfectly, but does not succeed on the assets, a message No Screenly API detected! - No data could be collected ...
Has anyone gone through this situation?
I'm Brazilian, sorry for my bad English

**Comment by didiatworkz** [comment]
Hello @c4rv88 
thanks for you congratulation 😄 
Normally, the message appears if this happened in line: [index.php:326](https://github.com/didiatworkz/screenly-ose-monitor/blob/246a48779c26fd91eaa43499f80a5eb6caa226a4/index.php#L326)

$playerAPICall is TRUE when the player is reachable and $playerAPI must not return the value "authentication error 401"!

Do you use the Screenly OSE Player with https:// protocol?
Do you activate the Basic authentication in the Screenly OSE Player settings and not enter the right data into the monitoring?

When both options are not the problem test if you can reach the player via curl command from your server via VPN, please.
```curl xxx.xxx.xxx.xxx```

Best,
didiatworkz

**Comment by c4rv88** [comment]
I already did a clean installation, I did not enable https. Even so, the error persists. I did the test with curl and I can access my pi. I will do other tests, thanks for the tips.

**Comment by didiatworkz** [comment]
You're welcome

**Comment by c4rv88** [comment]
Hi!
I haven't been successful in my settings yet!
Does he have any ip redirection?
My tests:

test ping :  Server - client interface tun0 [ok]
teste Ping: Server - client Interface  wlan0 [no sucess]

Test Ping:  client -  server interface tun0[ok]
teste ping: Client - Server Interface eth0[ok]

any tips?
Thank you!

**Comment by didiatworkz** [comment]
Hello @c4rv88 
there is no restriction from my side...
What I wonder is how you set up your VPN tunnel between the client and server (SSH, PiVPN or OpenConnet).

Maybe  @nsuva can help here as well, since he has already set up a working system via SSH tunnel.

If you look at your ping test, it looks like there might be a firewall not open or a forwarding is missing.
But unfortunately, I am no expert. :( 

I used the system in my company in the local network and it definitely works ;)

Best
didiatworkz
