### ISSUE TITLE
Tips for upgrade in new version

### ISSUE THREAD

**Issue by JurakZdenek** [didiatworkz/screenly-ose-monitor#56]
1) Add checkbox (and select/deselect all) on assests screen for multiple changes: start and end datetime, delete, active/inactive.

2) Add players groups - example: Dining rooms[player1,player5], All[player1,player2,player3,player4,player5], Firt floor[player1,player2], Second floor [player3,player4,player5]  
	its for better managment and for "add asset to multiple device".

3) Add option active/inactive, start, end, for new created asset - before upload. "Inactive" is important! .

**Comment by didiatworkz** [comment]
Hello @JurakZdenek 
thanks for your feedback!

# 1 - need time to implement but I guess it would be easy
# 2 -  sound like a small function but in the background I must check if it is possible at the moment
# 3 - I can implement this is V4.0 as well

# 1 and # 2 maybe in the following versions - I will add this to the projects board

**Comment by didiatworkz** [comment]
3. is implemented now

**Comment by JurakZdenek** [comment]
> 
> 
>     1. is implemented now

Perfect, you work quickly. Can I try it? or when will the new version be released?

**Comment by didiatworkz** [comment]
Hey,
I am currently testing the system completely. If you want to have a look at it already, you can install it like this.
However, I can't guarantee that something won't break at the moment! - Maybe I release this year or in the next. It depents on the free time that I have 😉 

```sh
bash <(curl -sL https://git.io/JL3vh)
```

**Comment by JurakZdenek** [comment]
> 
> 
>     1. is implemented now

Hi, can you add this option to Multi Uploader? Thank you :-)

**Comment by didiatworkz** [comment]
Oh what? - I forgot it 🙉 
I think you must update your system *hust* 😉

**Comment by c4rv88** [comment]
Hi!
First of all congratulations on the update of the tool, I installed it on my cloud server, did the multi-upload tests, groups and users.
I wanted to share a suggestion. In the dashboards screen, the ideal would be to show only information of the players that the user manages. what do you think?
I'm going to do some tests and give you feedback. but this is very show! congratulations one more time!

**Comment by didiatworkz** [comment]
Hello @c4rv88,

thanks for your feedback but create a new issue for one topic in the future, please - It's easier to handle that in the project plan!
Your suggestion is implemented. 😉 

@JurakZdenek - I close the Issue now! - I copy your ideas into the upcoming project plan: https://github.com/didiatworkz/screenly-ose-monitor/projects/4
