### ISSUE TITLE
SCHEDULE ASSETS TO PLAY ON DIFFERENT HOURS EVERYDAY

### ISSUE THREAD

**Issue by snipper1993** [didiatworkz/screenly-ose-monitor#92]
Hello,
Thank you for this application for screenly monitoring, is great.
I want if you can to add the feature wich I can schedule different assets on different hours everyday because now the screenly couldn't run multiple assets everyday, if i select to run for multiple day then it run the first asset always until stop day and no other asset will running.
Thank you,
Best Regards

**Comment by didiatworkz** [comment]
Hello @snipper1993 ,
I have looked at your suggestion and I am sorry to tell you that your idea is unfortunately not possible due to limitations of screenly OSE.
Unfortunately, I cannot implement it.

**Comment by snipper1993** [comment]
Thanks you so much for feedback, indeed the ose screenly is limited.
Have a great day!
