### ISSUE TITLE
Duda al traer la informacion 

### ISSUE THREAD

**Issue by omival-val** [didiatworkz/screenly-ose-monitor#93]
What's your question?
Good afternoon;
The following happens to me, I have the monitor installed on a server in the cloud with wireguard and I have a rapsberry with screenly pointing to the server with wireguard but it does not bring me the complete information and I have the monitor installed on a local computer where I have the raspberry and yes brings me all the complete information

I attach images, image 1 is from the server and image 2 is from the monitor that I have locally on the same network as the raspberry, something about the wireguard connection is not hissed

![imagen 1](https://user-images.githubusercontent.com/62353936/157715960-02b94bbe-7b2e-4780-873f-17970e4740e7.png)
![imagen2](https://user-images.githubusercontent.com/62353936/157716002-b648093b-d20f-4af7-bae5-09e10287daf8.png)

**Comment by didiatworkz** [comment]
Hello @omival-val 
SOMO is designed for running in local network environment - In the past there was some issues regarding ssh tunnels or VPN, but I can't support this.
In my productive environment, my Pi run in the same network as the players and everything work fine.

Best
didiatworkz
