### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by jmsf-pt** [didiatworkz/screenly-ose-monitor#94]
Database error when trying to install 4.3 version.
Any idea? 

![Sem Título](https://user-images.githubusercontent.com/102050070/159311130-ddd0e3aa-9744-4333-8702-dd6853f08a97.png)
?

**Comment by didiatworkz** [comment]
Hello @jmsf-pt 
SOMO is not built for windows installation.
Please use the docker image directly or the official installer with a Linux distro

Best
didiatworkz
