### ISSUE TITLE
Reset password?

### ISSUE THREAD

**Issue by sisensee** [didiatworkz/screenly-ose-monitor#95]
What's your question?
Is there a way to reset the sign-in password? I have managed to mistype the password twice. Thank you in advance.

**Comment by didiatworkz** [comment]
Hello @sisensee 

sorry for my late reply - Currently, there is only one option implemented:
Enter on your device where SOMO is installed this: `somo --reset`
This will remove the database and create a new one. Everything will be set back to default!
If you need to reset only the password, you need to edit the user table in the database and replace the password string with a md5 crypt password.

Best
didiatworkz
