### ISSUE TITLE
Need help with understand how it will work

### ISSUE THREAD

**Issue by zerenxyz** [didiatworkz/screenly-ose-monitor#96]
I have taken a look at Screenly OSE and SOMO however, I am a little consfused on how it will run fully. I understand I can run it on the same Pi as the player but do I need to install multiple versions of the SOMO on each Pi? As I have 10 Pi's with Screenly OSE on them how would I control them all from one install?

As well as would it work if I were to install SOMO alone on a Azure VM and connect somehow that way? Or it has to be on a local network that all are connected to (pi's and SOMO install)?

I am looking around for Digital Signage solutions and was aiming for PiSignage but it seems this project is more polished and up to date to be honest!

**Comment by didiatworkz** [comment]
Hello @zerenxyz,
You already recognise that partly correctly.
The project here can either be installed on a Linux server (Ubuntu/Debian recommended) or on a Screenly OSE player.
When the system is up and running, all devices from the local network are then connected via IP addresses.
From this point on, you can manage all devices from one place.
A few users also have the system running via SSH tunnel and can thus manage several locations.

Best
didiatworkz
