### ISSUE TITLE
video format

### ISSUE THREAD

**Issue by wk59er** [didiatworkz/screenly-ose-monitor#97]
What's your question?
Hello, I want to stream videos via screenly OSE. But I can't find the right video format, maybe someone can help me, please. 
With kind regards, 
Wolfgang

**Comment by nei-m** [comment]
1080p MP4 works for me

**Comment by didiatworkz** [comment]
Hello @wk59er,
please ask this question in the Screenly OSE repo - This project has nothing to do with your question.
But.. 1080 mp4 will work ;)

Best
didiatworkz
