### ISSUE TITLE
AddOn

### ISSUE THREAD

**Issue by nei-m** [didiatworkz/screenly-ose-monitor#99]
What's your question?
I've installed SOMO at another location on our network, but can't access it through port 9000. Do any other ports need opening up across the firewall? I can access the pi using SSH and have checked that SOMO is installed. I can telnet to the port, so it appears ok. SOMO looks not to be installed when viewing from the server I set up.
![Screenshot 2022-07-08 142137](https://user-images.githubusercontent.com/88782888/178000635-56bfbadd-75c8-4104-85f2-2194d641620e.jpg)
 is.

**Comment by didiatworkz** [comment]
Hello @nei-m,

you need to open the ports: 9020 and 9021 for the AddOn, too.
